version: '3.8'

services:
  bot:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - BINANCE_BASE_URL=${BINANCE_BASE_URL}
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - crypto_network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=crypto_bot
      - POSTGRES_USER=crypto_user
      - POSTGRES_PASSWORD=crypto_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - crypto_network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - crypto_network

volumes:
  postgres_data:
  redis_data:

networks:
  crypto_network:
    driver: bridge